version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 10.0
    commands:
      - echo "===== INSTALL PHASE ====="
      - dotnet --version

  pre_build:
    commands:
      - echo "===== RESTORE PHASE ====="
      - dotnet restore API/Taskverse.API/Taskverse.API.csproj

  build:
    commands:
      - echo "===== BUILD PHASE ====="
      - dotnet publish API/Taskverse.API/Taskverse.API.csproj -c Release -o publish

  post_build:
    commands:
      - echo "===== PREPARING DEPLOYMENT BUNDLE ====="

      - mkdir deployment

      - cp appspec-api.yml deployment/appspec.yml

      - cp taskverse-api.service deployment/

      - cp -r scripts deployment/

      - cp -r publish deployment/

      - ls -R deployment

artifacts:
  base-directory: deployment
  files:
    - '**/*'

cache:
  paths:
    - /root/.nuget/packages/**/*