version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 10.0

  build:
    commands:
      - echo "Publishing College Service..."
      - dotnet publish API/Taskverse.College.Service/Taskverse.API.College.Service.csproj -c Release -o publish
      - cp appspec-college.yml appspec.yml

artifacts:
  files:
    - publish/**/*
    - appspec.yml
    - taskverse-college.service
    - scripts/**/*